_wandb:
    value:
        cli_version: 0.19.2
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 71
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 71
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.2
            "6": 4.48.0
            "8":
                - 5
            "12": 0.19.2
            "13": linux-x86_64
BATCH_SIZE:
    value: 1
EPOCHS:
    value: 1
GRAD_ACCUM_STEPS:
    value: 1
LR:
    value: 1e-05
